optimization:
  weight_obstacle     : 100000.0
  weight_feasibility  : 10000.0
  weight_sqrvariance  : 10000.0
  weight_time         : 10.0
  obstacle_clearance  : 2.0
  load_dist           : 2.0
  max_vel             : 1.5
  max_acc             : 2.0
  load_mass           : 2.0

cable:
  cable_length        : 4.0
  uav_obs_clearance   : 2.0
  uav_swarm_clearance : 2.0
  cable_clearance     : 1.0
  weight_uav_obs      : 100000.0
  weight_uav_swarm    : 100000.0
  weight_FM_feasibility : 10000.0 
  # weight_FM_norm      : 0.0  
  weight_cable_collision: 100000.0
  # wei_tq1_vel: 0.0
  cable_piece         : 5  # number of cable segments
  # max_tq1_vel: 20
  wei_energy: 50

lbfgs_params:
  mem_size : 10       #default value 6
  g_epsilon: 0  #default value 1.0e-5
  past: 3            #default value 0
  delta: 1.0e-5      #default value 1.0e-5
  max_iterations: 0  #default value 0
  min_step: 1.0e-32  #default value 1.0e-20


fsm:
  replan_trajectory_time : 0.1   # s, the max time of replanning trajectory
